CREATE DATABASE IF NOT EXISTS ACLC;
USE ACLC;


-- CREATE TABLE student(
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     fullname VARCHAR(255) NOT NULL,
--     gmail VARCHAR(255) NOT NULL,
--     phoneNumber VARCHAR(50) NOT NULL,
--     hometown VARCHAR (255) NOT NULL,
--     grade INT(50) NOT NULL,
--     section VARCHAR(50) NOT NULL,
--     strand VARCHAR(255) NOT NULL
-- );

CREATE TABLE admin(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    gmail VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);